DevApi.Challenge/Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;

namespace DevApi.Challenge.Models
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) 
        {
            //Database.EnsureCreated();
        }
        public DbSet<Developer> Developers { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            //optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=TempProsoftDevTest;Integrated Security=true");
            optionsBuilder.UseSqlServer(@"Server=deploydbdev.database.windows.net;Database=deploydbdev;User Id=dbazure;Password=1233Mm!!;");
        }
        
    }
}

DevApi.Challenge/Models/Developer.cs
namespace DevApi.Challenge.Models
{
    public class Developer
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
        public string Squad { get; set; } = string.Empty;
        public string Login { get; set; } = string.Empty;
        public string Avatar { get; set; } = string.Empty;
        public string? Tag { get; set; } = string.Empty;
        public DateTime? DtCreation { get; set; }
        public DateTime? CreatedAt { get; set; }

    }
}

DevApi.Challenge/Models/ErrorViewModel.cs
namespace DevApi.Challenge.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DevApi.Challenge/Controllers/DevelopersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DevApi.Challenge.Models;

namespace DevApi.Challenge.Controllers
{
    public class DevelopersController : Controller
    {
        private readonly AppDbContext _context;
        ILogger<DevelopersController> _logger;

        public DevelopersController(AppDbContext context, ILogger<DevelopersController> logger)
        {
            _context = context;
            _logger = logger;
            
        }

        // GET: Developers
        public async Task<IActionResult> Index()
        {
              return _context.Developers != null ? 
                          View(await _context.Developers.ToListAsync()) :
                          Problem("Entity set 'AppDbContext.Developers'  is null.");
        }

        // GET: Developers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Developers == null)
            {
                return NotFound();
            }

            var developer = await _context.Developers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (developer == null)
            {
                return NotFound();
            }

            return View(developer);
        }

        // GET: Developers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Developers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,Squad,Login,Avatar,Tag,DtCreation,CreatedAt")] Developer developer)
        {
            if(!developer.Email.Contains("@prosoft"))
            {
                throw new Exception("Prosoft Email Domain is not valid");
            }

            if (ModelState.IsValid)
            {
                _context.Add(developer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(developer);
        }

        // GET: Developers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Developers == null)
            {
                return NotFound();
            }

            var developer = await _context.Developers.FindAsync(id);
            if (developer == null)
            {
                return NotFound();
            }
            return View(developer);
        }

        // POST: Developers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,Squad,Login,Avatar,Tag,DtCreation,CreatedAt")] Developer developer)
        {
            if (id != developer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(developer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeveloperExists(developer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(developer);
        }

        // GET: Developers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Developers == null)
            {
                return NotFound();
            }

            var developer = await _context.Developers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (developer == null)
            {
                return NotFound();
            }

            return View(developer);
        }

        // POST: Developers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Developers == null)
            {
                return Problem("Entity set 'AppDbContext.Developers'  is null.");
            }
            var developer = await _context.Developers.FindAsync(id);
            if (developer != null)
            {
                _context.Developers.Remove(developer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DeveloperExists(int id)
        {
          return (_context.Developers?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

DevApi.Challenge/Controllers/HomeController.cs
using DevApi.Challenge.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DevApi.Challenge.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DevApi.Challenge/Views/Developers/Create.cshtml
@model DevApi.Challenge.Models.Developer

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Developer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Squad" class="control-label"></label>
                <input asp-for="Squad" class="form-control" />
                <span asp-validation-for="Squad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Avatar" class="control-label"></label>
                <input asp-for="Avatar" class="form-control" />
                <span asp-validation-for="Avatar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tag" class="control-label"></label>
                <input asp-for="Tag" class="form-control" />
                <span asp-validation-for="Tag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DtCreation" class="control-label"></label>
                <input asp-for="DtCreation" class="form-control" />
                <span asp-validation-for="DtCreation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DevApi.Challenge/Views/Developers/Delete.cshtml
@model DevApi.Challenge.Models.Developer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Developer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Squad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Squad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Login)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Login)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Avatar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Avatar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DtCreation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DtCreation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DevApi.Challenge/Views/Developers/Details.cshtml
@model DevApi.Challenge.Models.Developer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Developer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Squad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Squad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Login)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Login)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Avatar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Avatar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DtCreation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DtCreation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DevApi.Challenge/Views/Developers/Edit.cshtml
@model DevApi.Challenge.Models.Developer

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Developer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Squad" class="control-label"></label>
                <input asp-for="Squad" class="form-control" />
                <span asp-validation-for="Squad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Avatar" class="control-label"></label>
                <input asp-for="Avatar" class="form-control" />
                <span asp-validation-for="Avatar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tag" class="control-label"></label>
                <input asp-for="Tag" class="form-control" />
                <span asp-validation-for="Tag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DtCreation" class="control-label"></label>
                <input asp-for="DtCreation" class="form-control" />
                <span asp-validation-for="DtCreation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DevApi.Challenge/Views/Developers/Index.cshtml
@model IEnumerable<DevApi.Challenge.Models.Developer>

@{
    ViewData["Title"] = "Index";
}

<h1>Developers Endpoints</h1>

<p>
    <a asp-action="Create">Post New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Squad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Login)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Avatar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tag)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DtCreation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Squad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Login)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Avatar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tag)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DtCreation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details View</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

DevApi.Challenge/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-left">
    <h1>Hello Alterdata/Prosoft!</h1>
    <p>Welcome to our application, built with:</p>
    <ul>
        <li><a href='https://get.asp.net/'>ASP.NET Core</a> and <a href='https://msdn.microsoft.com/en-us/library/67ef8sbd.aspx'>C#</a> for cross-platform server-side code</li>
        <li><a href='https://learn.microsoft.com/pt-br/ef/'>EntityFramework</a> for client-side code</li>
        <li><a href='https://learn.microsoft.com/pt-br/aspnet/core/mvc/views/razor?view=aspnetcore-7.0'>Web Forms</a> for layout and styling</li>
        <li><a href='https://sql.digital/pt-br/sql-server/sql-server-downloads/SQL_Server.php'>SQL Server</a> for database</li>
    </ul>
    <p>To help you get started, we have:</p>
    <ul>
        <li><strong>Table</strong>. You just need to choose a <em>Developer</em>. In single one, <em>Details</em> show a specific data.</li>
        <li><strong>Migration</strong>. In development mode, the development server from <code>Update-Database</code> runs in the background automatically in deploy enviroment.</li>
        <li><strong>Azure Deploy</strong>. This application is using <code>DevOps</code> tools, efficiently bundled with Database.</li>
    </ul>   
</div>

DevApi.Challenge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DevApi.Challenge</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DevApi.Challenge.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DevApi.Challenge</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Developers" asp-action="Index">Developers Api</a>
                        </li>                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DevApi.Challenge - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>